//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// MyToolbox.rc で使用
//
#define IDC_MYICON                      2
#define IDI_MYTOOLBOX                   10
#define IDI_SMALL                       11
#define IDS_APP_TITLE                   100
#define IDS_MENU_FILE                   110
#define IDS_MENU_EDIT                   111
#define IDS_MENU_VIEW                   112
#define IDS_MENU_SETTINGS               113
#define IDS_MENU_HELP                   114
#define IDS_MENU_EXIT                   115
#define IDS_MENU_ABOUT                  116
#define IDS_MENU_CUT                    117
#define IDS_MENU_COPY                   118
#define IDS_MENU_PASTE                  119
#define IDS_MENU_DELETE                 120
#define IDS_MENU_SELECTALL              121
#define IDS_MENU_COPYALL                122
#define IDS_MENU_COPYRESULT             123
#define IDS_MENU_CLEAR                  124
#define IDS_MENU_CALCULATE              125
#define IDS_MENU_NEW                    126
#define IDS_MENU_ENCODE                 127
#define IDS_MENU_DECODE                 128
#define IDS_MENU_LOADFROM               129
#define IDS_MENU_SAVEAS                 130
#define IDS_MENU_HASH                   131
#define IDS_MENU_CRPT                   132
#define IDS_MENU_GUID                   133
#define IDS_MENU_PCTC                   134
#define IDS_MENU_CRON                   135
#define IDS_MENU_NTOA                   136
#define IDS_MENU_DTTM                   137
#define IDS_MENU_SFID                   138
#define IDS_MENU_CODE                   139
#define IDS_MENU_CLIP                   140
#define IDS_MENU_IENCODING              141
#define IDS_MENU_OENCODING              142
#define IDS_MENU_AUTODETECT             143
#define IDS_MENU_UTF8                   144
#define IDS_MENU_UTF8BOM                145
#define IDS_MENU_UTF16                  146
#define IDS_MENU_UTF16BOM               147
#define IDS_MENU_CP932                  148
#define IDS_MENU_CP936                  149
#define IDS_MENU_CP949                  150
#define IDS_MENU_CP950                  151
#define IDS_MENU_CP1250                 152
#define IDS_MENU_CP1251                 153
#define IDS_MENU_CP1252                 154
#define IDS_MENU_CP1253                 155
#define IDS_MENU_CP1254                 156
#define IDS_MENU_CP1255                 157
#define IDS_MENU_CP1256                 158
#define IDS_MENU_CP1257                 159
#define IDS_MENU_CP1258                 160
#define IDS_MENU_ALGORITHM              161
#define IDS_MENU_MD5                    162
#define IDS_MENU_SHA1                   163
#define IDS_MENU_SHA256                 164
#define IDS_MENU_SHA384                 165
#define IDS_MENU_SHA512                 166
#define IDS_MENU_FORMAT                 167
#define IDS_MENU_UPPERCASE              168
#define IDS_MENU_LOWERCASE              169
#define IDS_MENU_USESECOND              170
#define IDS_MENU_LOADORGFROM            171
#define IDS_MENU_SAVEORGAS              172
#define IDS_MENU_LOADENCFROM            173
#define IDS_MENU_SAVEENCAS              174
#define IDS_MENU_WRAPDATA               175
#define IDS_TAB_HASH                    190
#define IDS_TAB_CRPT                    191
#define IDS_TAB_GUID                    192
#define IDS_TAB_PCTC                    193
#define IDS_TAB_CRON                    194
#define IDS_TAB_NTOA                    195
#define IDS_TAB_DTTM                    196
#define IDS_TAB_SFID                    197
#define IDS_TAB_CODE                    198
#define IDS_TAB_CLIP                    199
#define IDS_OUT_OF_MEMORY               200
#define IDS_UNKNOWN_FAILURE             201
#define IDS_RESULT                      202
#define IDC_MYTOOLBOX                   203
#define IDS_RESULT_IN                   204
#define IDS_RESULT_IN_OUT               205
#define IDS_OPENFILE_FAILURE            207
#define IDS_READFILE_FAILURE            208
#define IDS_PCTC_ERROR                  211
#define IDS_MSG_CLIPBOARD_COPY_ERROR    213
#define IDS_MSG_CLIPBOARD_PASTE_ERROR   214
#define IDS_LOADTEXTFROMFILE            216
#define IDS_MSG_TOO_LARGE_FILE          217
#define IDS_SAVETEXTASFILE              218
#define IDS_MSG_TEXT_ENCODING_CONVERSION_ERROR 219
#define IDS_MSG_FILE_WRITE_ERROR        220
#define IDD_HASH                        800
#define IDD_CRPT                        801
#define IDD_GUID                        802
#define IDD_PCTC                        803
#define IDD_CRON                        804
#define IDD_NTOA                        805
#define IDD_DTTM                        806
#define IDD_SFID                        807
#define IDD_CODE                        808
#define IDD_CLIP                        809
#define IDD_ABOUTBOX                    890
#define IDC_ABOUT_HEADER_STATIC         990
#define IDC_ABOUT_VERSION_STATIC        991
#define IDC_ABOUT_COPYRIGHT_STATIC      992
#define IDC_HASH_FILE_RADIO             1000
#define IDC_HASH_PATH_EDIT              1001
#define IDC_HASH_BROWSE_BUTTON          1002
#define IDC_HASH_TEXT_RADIO             1003
#define IDC_HASH_CONTENT_EDIT           1004
#define IDC_HASH_CODEPAGE_COMBO         1005
#define IDC_HASH_LINEBREAK_COMBO        1006
#define IDC_HASH_MD5_RADIO              1007
#define IDC_HASH_SHA1_RADIO             1008
#define IDC_HASH_SHA256_RADIO           1009
#define IDC_HASH_SHA384_RADIO           1010
#define IDC_HASH_SHA512_RADIO           1011
#define IDC_HASH_VALUE_STATIC           1012
#define IDC_HASH_UPPERCASE_CHECK        1013
#define IDC_HASH_CALCULATE_BUTTON       1014
#define IDC_HASH_COPY_BUTTON            1015
#define IDC_HASH_RESULT_GROUP           1016
#define IDC_HASH_ALGORITHM_GROUP        1017
#define IDC_HASH_FORMAT_GROUP           1018
#define IDC_HASH_SOURCE_GROUP           1019
#define IDC_GUID_UPPERCASE_RADIO        2000
#define IDC_GUID_LOWERCASE_RADIO        2001
#define IDC_GUID_IMPLEMENT_RADIO        2002
#define IDC_GUID_DEFINE_RADIO           2003
#define IDC_GUID_STRUCT_RADIO           2004
#define IDC_GUID_REGISTRY_RADIO         2005
#define IDC_GUID_SQUARE_RADIO           2006
#define IDC_GUID_ANGLE_RADIO            2007
#define IDC_GUID_RESULT_STATIC          2008
#define IDC_GUID_HEX_RADIO              2009
#define IDC_GUID_COPY_BUTTON            2010
#define IDC_GUID_NEW_BUTTON             2011
#define IDC_PCTC_CONTENT1_RADIO         3000
#define IDC_PCTC_CONTENT2_RADIO         3001
#define IDC_PCTC_DESC_STATIC            3002
#define IDC_PCTC_CONTENT1_EDIT          3003
#define IDC_PCTC_CONTENT2_EDIT          3004
#define IDC_PCTC_ENCODE_BUTTON          3005
#define IDC_PCTC_DECODE_BUTTON          3006
#define IDC_PCTC_CODEPAGE_COMBO         3007
#define IDC_PCTC_STATUS1_STATIC         3008
#define IDC_PCTC_STATUS2_STATIC         3009
#define IDC_PCTC_COPY2_BUTTON           3010
#define IDC_PCTC_COPY1_BUTTON           3011
#define IDC_PCTC_USEPLUS_CHECK          3012
#define IDC_CRON_EXPR_EDIT              4000
#define IDC_CRON_EXPR_COMBO             4001
#define IDC_CRON_EXPR_STATIC            4009
#define IDC_CRON_YEAR_STATIC            4110
#define IDC_CRON_YEAR_ALL_RADIO         4111
#define IDC_CRON_YEAR_EXPR_RADIO        4112
#define IDC_CRON_YEAR_EDIT              4118
#define IDC_CRON_YEAR_EVAL_STATIC       4119
#define IDC_CRON_MONTH_STATIC           4120
#define IDC_CRON_MONTH_ALL_RADIO        4121
#define IDC_CRON_MONTH_EXPR_RADIO       4122
#define IDC_CRON_MONTH_EDIT             4123
#define IDC_CRON_MONTH_EVAL_STATIC      4129
#define IDC_CRON_DAY_STATIC             4130
#define IDC_CRON_DAY_ALL_RADIO          4131
#define IDC_CRON_DAY_ANY_RADIO          4132
#define IDC_CRON_DAY_LASTDAY_RADIO      4133
#define IDC_CRON_DAY_WEEKDAY_RADIO      4134
#define IDC_CRON_DAY_EXPR_RADIO         4135
#define IDC_CRON_DAY_EDIT               4136
#define IDC_CRON_DAY_EVAL_STATIC        4139
#define IDC_CRON_DOW_STATIC             4140
#define IDC_CRON_DOW_ALL_RADIO          4141
#define IDC_CRON_DOW_ANY_RADIO          4142
#define IDC_CRON_DOW_EXPR_RADIO         4143
#define IDC_CRON_DOW_EDIT               4144
#define IDC_CRON_DOW_EVAL_STATIC        4149
#define IDC_CRON_HOUR_STATIC            4150
#define IDC_CRON_HOUR_ALL_RADIO         4151
#define IDC_CRON_HOUR_EXPR_RADIO        4152
#define IDC_CRON_HOUR_EDIT              4153
#define IDC_CRON_HOUR_EVAL_STATIC       4159
#define IDC_CRON_MINUTE_STATIC          4160
#define IDC_CRON_MINUTE_ALL_RADIO       4161
#define IDC_CRON_MINUTE_EXPR_RADIO      4162
#define IDC_CRON_MINUTE_EDIT            4163
#define IDC_CRON_MINUTE_EVAL_STATIC     4169
#define IDC_CRON_SECOND_STATIC          4170
#define IDC_CRON_SECOND_ALL_RADIO       4171
#define IDC_CRON_SECOND_EXPR_RADIO      4172
#define IDC_CRON_SECOND_EDIT            4173
#define IDC_CRON_SECOND_EVAL_STATIC     4179
#define IDC_CRON_DESC_EDIT              4200
#define IDC_CRON_OFFSET_COMBO           4300
#define IDC_CRON_SECOND_CHECK           4301
#define IDC_CRON_COPY_BUTTON            4900
#define IDC_NTOA_NATIVE_RADIO           5000
#define IDC_NTOA_ASCII_RADIO            5001
#define IDC_NTOA_NATIVE_EDIT            5002
#define IDC_NTOA_COPY1_BUTTON           5003
#define IDC_NTOA_ENCODE_BUTTON          5004
#define IDC_NTOA_ASCII_EDIT             5005
#define IDC_NTOA_COPY2_BUTTON           5006
#define IDC_NTOA_DECODE_BUTTON          5007
#define IDC_CLIP_FILENAME_LIST          6000
#define IDC_CLIP_HEADER_STATIC          6001
#define IDC_CLIP_HEADER_EDIT            6002
#define IDC_CLIP_BODY_STATIC            6003
#define IDC_CLIP_BODY_EDIT              6004
#define IDC_CLIP_COPY_BUTTON            6005
#define IDC_CLIP_DELETE_BUTTON          6006
#define IDC_CRPT_AESCBC_RADIO           7000
#define IDC_CRPT_AESECB_RADIO           7001
#define IDC_CRPT_AESCFB_RADIO           7002
#define IDC_CRPT_AESCCM_RADIO           7003
#define IDC_CRPT_AESGCM_RADIO           7004
#define IDC_CRPT_KEY_EDIT               7020
#define IDC_CRPT_KEY128_RADIO           7021
#define IDC_CRPT_KEY192_RADIO           7022
#define IDC_CRPT_KEY256_RADIO           7023
#define IDC_CRPT_IV_EDIT                7030
#define IDC_CRPT_IVLEN_STATIC           7031
#define IDC_CRPT_NONCE_EDIT             7040
#define IDC_CRPT_NONCE11_RADIO          7041
#define IDC_CRPT_NONCE12_RADIO          7042
#define IDC_CRPT_NONCE13_RADIO          7043
#define IDC_CRPT_NONCE14_RADIO          7044
#define IDC_CRPT_TAG_EDIT               7050
#define IDC_CRPT_TAG4_RADIO             7051
#define IDC_CRPT_TAG6_RADIO             7052
#define IDC_CRPT_TAG8_RADIO             7053
#define IDC_CRPT_TAG10_RADIO            7054
#define IDC_CRPT_TAG12_RADIO            7055
#define IDC_CRPT_TAG14_RADIO            7056
#define IDC_CRPT_TAG16_RADIO            7057
#define IDC_CRPT_ORG_EDIT               7061
#define IDC_CRPT_ORG_HEX_RADIO          7062
#define IDC_CRPT_ORG_BASE64_RADIO       7063
#define IDC_CRPT_ORG_RAW_RADIO          7064
#define IDC_CRPT_ORG_ENC_COMBO          7065
#define IDC_CRPT_ENC_STATIC             7070
#define IDC_CRPT_ENC_EDIT               7071
#define IDC_CRPT_ENC_HEX_RADIO          7072
#define IDC_CRPT_ENC_BASE64_RADIO       7073
#define IDC_CRPT_STATUS_STATIC          7080
#define IDC_CRPT_ENCRYPT_BUTTON         7090
#define IDC_CRPT_DECRYPT_BUTTON         7091
#define IDC_DTTM_EDIT                   8000
#define IDC_DTTM_COPY_BUTTON            8001
#define IDC_DTTM_NEW_BUTTON             8002
#define IDC_DTTM_YEAR_STATIC            8011
#define IDC_DTTM_YEAR_EDIT              8012
#define IDC_DTTM_YEAR_CHECK             8013
#define IDC_DTTM_MONTH_STATIC           8021
#define IDC_DTTM_MONTH_EDIT             8022
#define IDC_DTTM_MONTH_CHECK            8023
#define IDC_DTTM_DAY_STATIC             8031
#define IDC_DTTM_DAY_EDIT               8032
#define IDC_DTTM_DAY_CHECK              8033
#define IDC_DTTM_HOUR_STATIC            8041
#define IDC_DTTM_HOUR_EDIT              8042
#define IDC_DTTM_HOUR_CHECK             8043
#define IDC_DTTM_MINUTE_STATIC          8051
#define IDC_DTTM_MINUTE_EDIT            8052
#define IDC_DTTM_MINUTE_CHECK           8053
#define IDC_DTTM_SECOND_STATIC          8061
#define IDC_DTTM_SECOND_EDIT            8062
#define IDC_DTTM_SECOND_CHECK           8063
#define IDC_DTTM_MILLISECOND_STATIC     8071
#define IDC_DTTM_MILLISECOND_EDIT       8072
#define IDC_DTTM_MILLISECOND_CHECK      8073
#define IDC_DTTM_OFFSET_STATIC          8081
#define IDC_DTTM_OFFSET_COMBO           8082
#define IDC_DTTM_DTZ_EXTENDED_RADIO     8101
#define IDC_DTTM_DTZ_BASIC_RADIO        8102
#define IDC_DTTM_DMZ_EXTENDED_RADIO     8103
#define IDC_DTTM_DMZ_BASIC_RADIO        8104
#define IDC_DTTM_TZ_EXTENDED_RADIO      8111
#define IDC_DTTM_TZ_BASIC_RADIO         8112
#define IDC_DTTM_MZ_EXTENDED_RADIO      8113
#define IDC_DTTM_MZ_BASIC_RADIO         8114
#define IDC_DTTM_DT_EXTENDED_RADIO      8121
#define IDC_DTTM_DT_BASIC_RADIO         8122
#define IDC_DTTM_DT_NOSEP_RADIO         8123
#define IDC_DTTM_DM_EXTENDED_RADIO      8131
#define IDC_DTTM_DM_BASIC_RADIO         8132
#define IDC_DTTM_DM_NOSEP_RADIO         8133
#define IDC_DTTM_UTC_DTZ_EXTENDED_RADIO 8141
#define IDC_DTTM_UTC_DTZ_BASIC_RADIO    8142
#define IDC_DTTM_UTC_DMZ_EXTENDED_RADIO 8143
#define IDC_DTTM_UTC_DMZ_BASIC_RADIO    8144
#define IDC_DTTM_UTC_TZ_EXTENDED_RADIO  8151
#define IDC_DTTM_UTC_TZ_BASIC_RADIO     8152
#define IDC_DTTM_UTC_MZ_EXTENDED_RADIO  8153
#define IDC_DTTM_UTC_MZ_BASIC_RADIO     8154
#define IDC_DTTM_DATEONLY_EXTENDED_RADIO 8161
#define IDC_DTTM_DATEONLY_SLASH_RADIO   8162
#define IDC_DTTM_DATEONLY_PERIOD_RADIO  8163
#define IDC_DTTM_DATEONLY_BASIC_RADIO   8164
#define IDC_DTTM_TIMEONLY_EXTENDED_RADIO 8171
#define IDC_DTTM_TIMEONLY_BASIC_RADIO   8172
#define IDC_DTTM_TIMEONLY_MS_EXTENDED_RADIO 8173
#define IDC_DTTM_TIMEONLY_MS_BASIC_RADIO 8174
#define IDC_DTTM_SECONDS_RADIO          8181
#define IDC_DTTM_MILLISECONDS_RADIO     8182
#define IDC_DTTM_FILETIME_RADIO         8183
#define IDC_SFID_EDIT                   9000
#define IDC_SFID_STATUS_STATIC          9001
#define IDC_SFID_KEYPREFIX_EDIT         9002
#define IDC_SFID_INSTANCE_EDIT          9003
#define IDC_SFID_UNIQUEID_EDIT          9004
#define IDC_SFID_CHECKSUM_EDIT          9005
#define IDC_SFID_COPY_BUTTON            9006
#define IDC_SFID_NEW_BUTTON             9007
#define IDC_SFID_UP_BUTTON              9008
#define IDC_SFID_DOWN_BUTTON            9009
#define IDC_CODE_GTIN13_STATIC          10000
#define IDC_CODE_GTIN13_EDIT            10001
#define IDC_CODE_GTIN13_COPY_BUTTON     10002
#define IDC_CODE_GTIN13_UP_BUTTON       10003
#define IDC_CODE_GTIN13_DN_BUTTON       10004
#define IDM_FILE_EXIT                   11001
#define IDM_FILE_LOADFROM               11002
#define IDM_FILE_SAVEAS                 11003
#define IDM_FILE_LOAD1FROM              11004
#define IDM_FILE_SAVE1AS                11005
#define IDM_FILE_LOAD2FROM              11006
#define IDM_FILE_SAVE2AS                11007
#define IDM_EDIT_CUT                    12001
#define IDM_EDIT_COPY                   12002
#define IDM_EDIT_PASTE                  12003
#define IDM_EDIT_DELETE                 12004
#define IDM_EDIT_SELECTALL              12005
#define IDM_EDIT_COPYALL                12006
#define IDM_EDIT_CLEAR                  12007
#define IDM_EDIT_EXECUTE                12008
#define IDM_VIEW_HASH                   13001
#define IDM_VIEW_CRPT                   13002
#define IDM_VIEW_GUID                   13003
#define IDM_VIEW_PCTC                   13004
#define IDM_VIEW_CRON                   13005
#define IDM_VIEW_NTOA                   13006
#define IDM_VIEW_DTTM                   13007
#define IDM_VIEW_SFID                   13008
#define IDM_VIEW_CODE                   13009
#define IDM_VIEW_CLIP                   13010
#define IDM_SETTINGS_IN_AUTO            14000
#define IDM_SETTINGS_IN_UTF8            14001
#define IDM_SETTINGS_IN_UTF16           14003
#define IDM_SETTINGS_IN_CP932           14005
#define IDM_SETTINGS_IN_CP936           14006
#define IDM_SETTINGS_IN_CP949           14007
#define IDM_SETTINGS_IN_CP950           14008
#define IDM_SETTINGS_IN_CP1250          14009
#define IDM_SETTINGS_IN_CP1251          14010
#define IDM_SETTINGS_IN_CP1252          14011
#define IDM_SETTINGS_IN_CP1253          14012
#define IDM_SETTINGS_IN_CP1254          14013
#define IDM_SETTINGS_IN_CP1255          14014
#define IDM_SETTINGS_IN_CP1256          14015
#define IDM_SETTINGS_IN_CP1257          14016
#define IDM_SETTINGS_IN_CP1258          14017
#define IDM_SETTINGS_OUT_UTF8           14021
#define IDM_SETTINGS_OUT_UTF8BOM        14022
#define IDM_SETTINGS_OUT_UTF16          14023
#define IDM_SETTINGS_OUT_UTF16BOM       14024
#define IDM_SETTINGS_OUT_CP932          14025
#define IDM_SETTINGS_OUT_CP936          14026
#define IDM_SETTINGS_OUT_CP949          14027
#define IDM_SETTINGS_OUT_CP950          14028
#define IDM_SETTINGS_OUT_CP1250         14029
#define IDM_SETTINGS_OUT_CP1251         14030
#define IDM_SETTINGS_OUT_CP1252         14031
#define IDM_SETTINGS_OUT_CP1253         14032
#define IDM_SETTINGS_OUT_CP1254         14033
#define IDM_SETTINGS_OUT_CP1255         14034
#define IDM_SETTINGS_OUT_CP1256         14035
#define IDM_SETTINGS_OUT_CP1257         14036
#define IDM_SETTINGS_OUT_CP1258         14037
#define IDM_SETTINGS_MD5                14040
#define IDM_SETTINGS_SHA1               14041
#define IDM_SETTINGS_SHA256             14042
#define IDM_SETTINGS_SHA384             14043
#define IDM_SETTINGS_SHA512             14044
#define IDM_SETTINGS_UPPERCASE          14050
#define IDM_SETTINGS_LOWERCASE          14051
#define IDM_SETTINGS_USESECOND          14052
#define IDM_SETTINGS_WRAPDATA           14053
#define IDM_HELP_ABOUT                  19001
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         10003
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
