//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// HostsUpdater.rc で使用
//
#define IDS_SERVICE_NAME                101
#define IDS_SERVICE_DISPLAY_NAME        102
#define IDS_SERVICE_DESCRIPTION         103
#define IDS_ERROR_UNEXPECTED_EXCEPTION  104
#define IDS_ERROR_MESSAGE               105
#define IDS_ERROR_MESSAGE_CODE_REASON   106
#define IDS_WARNING_WSINIT_FAILURE      107
#define IDS_UNEXPECTED_COMMAND          108
#define IDS_INVALID_COMMAND             109
#define IDS_TOO_MANY_ARGS               110
#define IDS_USAGE                       111
#define IDS_INFO_CREATED_SERVICE        112
#define IDS_INFO_SERVICE_IS_RUNNING     113
#define IDS_INFO_SERVICE_IS_SUSPENDED   114
#define IDS_INFO_SERVICE_IS_NOT_STOPPED 115
#define IDS_INFO_STOPPING_SERVICE       116
#define IDS_INFO_STOPPED_SERVICE        117
#define IDS_INFO_DELETED_SERVICE        118
#define IDS_FAILED_START_SVC_CTRL_DISPATCHER 119
#define IDS_WARNING_REGISTRY_MISSING_CREATING 120
#define IDS_WARNING_REGISTRY_UNAVAILABLE 121
#define IDS_INFO_FOUND_REGISTRY_VERSION_1_UNDER_HKLM 122
#define IDS_WARNING_REGISTRY_UNEXPECTED_VALUE_LU 123
#define IDS_INFO_CREATED_REGISTRY_VERSION_1_UNDER_HKLM 124
#define IDS_INFO_CREATED_DIRECTORY      125
#define IDS_WARNING_FAILED_CREATE_DIRECTORY 126
#define IDS_INFO_APPDIR_IS              127
#define IDS_INVALID_PARAMETER           128
#define IDS_FAILED_PARSE                129
#define IDS_FAILED_OPEN                 130
#define IDS_FAILED_GETSIZE              131
#define IDS_FAILED_READ                 132
#define IDS_FAILED_READ_SIZE_MISMATCH   133
#define IDS_FAILED_REWIND               134
#define IDS_FAILED_WRITE                135
#define IDS_FAILED_WRITE_SIZE_MISMATCH  136
#define IDS_FAILED_SETSIZE              137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
